language: python

services:
  - docker

cache: pip

env:
  # Tell Qt not to require bringing up a GUI
  - QT_QPA_PLATFORM="offscreen"
  - _API_HOST="localhost"
  - _API_PORT=8080

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! [[ -x "$(command -v pyenv)" ]]; then brew install pyenv ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install 3.6.3 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH="~/.pyenv/versions/3.6.3/bin:$PATH" ; fi
    - mkdir -p /tmp/api
    - git clone https://github.com/deepmarket/api.git /tmp/api
    - cd /tmp/api && docker-compose up -d --build
    - cd $TRAVIS_BUILD_DIR

install:
  - python -m pip install pipenv
  - pipenv install

script:
  - pipenv run python -m unittest discover ./src/unittest/python
  # xvfb allows GUI applications to run headlessly and only works on xenial
  # See: https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-the-xvfb-run-wrapper
  - pipenv run xvfb-run behave ./src/integrationtest/python

matrix:
  include:
    # Tests Python 3.6 on Ubuntu Xenial
    - python: "3.6"
      dist: xenial
      sudo: true


