language: python

cache: pip

env:
  # Tell Qt not to require bringing up a GUI
  - QT_QPA_PLATFORM="offscreen"
  # This is a workaround baked into the application if the former doesn't work
  - HEADLESS="true"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest test/test_api.py
  - python -m behave test/features

matrix:
  include:

    # Tests Python 3.6 on Ubuntu Trusty (14.04)
    - python: "3.6"
#    - python: 3.7  # as of 8/17/18 3.7 is still being worked on by the travis team
      dist: trusty
      sudo: true

    # Tests Python 3.6 and 3.7 on Ubuntu Xenial (16.04)
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true

    # MacOs
    # See https://docs.travis-ci.com/user/reference/osx/#os-x-version for details

    # 10.11.latest
    - os: osx
      language: generic
      osx_image: xcode8

    # 10.12.latest
    - os: osx
      language: generic
      osx_image: xcode9.2

    # 10.13.latest
    - os: osx
      language: generic
      osx_image: xcode10
  
  
  allow_failures:
    # 10.10
    - os: osx
      language: generic
      osx_image: xcode6.4


# Perform manual install of 3.6 for OS X
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! [[ -x "$(command -v pyenv)" ]]; then brew install pyenv ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install 3.6.3 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH="~/.pyenv/versions/3.6.3/bin:$PATH" ; fi

