language: python

cache: pip

env:
  # Tell Qt not to require bringing up a GUI
  - QT_QPA_PLATFORM="offscreen"
  # This is a workaround baked into the application if the former doesn't work
  - HEADLESS="true"

install:
    - python --version
    - python -m pip install pipenv
    - pipenv install

script:
    - pipenv run python -m unittest discover ./src/unittest/python
    # xvfb allows GUI applications to run headlessly and only works on xenial
    # See: https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-the-xvfb-run-wrapper 
    - xvfb-run behave ./src/integrationtest/python

matrix:
  include:
# As of 3/6/19 Trusty does not work with PyQt5 in CI

    # Tests Python 3.6 on Ubuntu Trusty
#    - python: 3.6
#    - no 3.7 until pipenv + fbs get up to it
#      dist: trusty
#      sudo: true

    # Tests Python 3.6 on Ubuntu Xenial
    - python: "3.6"
      dist: xenial
      # services:
      #   - xvfb
      sudo: true

    - python: "3.6"
      dist: bionic
      services:
        xvfb
      sudo: true

    # MacOs
    # See https://docs.travis-ci.com/user/reference/osx/#os-x-version for details

#    # 10.11.latest
#    - os: osx
#      language: generic
#      osx_image: xcode8
#
#    # 10.12.latest
#    - os: osx
#      language: generic
#      osx_image: xcode9.2
#
#    # 10.13.latest
#    - os: osx
#      language: generic
#      osx_image: xcode10
#
#
#  allow_failures:
#    # 10.10
#    - os: osx
#      language: generic
#      osx_image: xcode6.4

# Perform manual install of 3.6 for OS X
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! [[ -x "$(command -v pyenv)" ]]; then brew install pyenv ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install 3.6.3 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH="~/.pyenv/versions/3.6.3/bin:$PATH" ; fi

